# fly.toml app configuration file generated for eventsc-fix on 2025-07-23T20:31:09-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

#this is the production configuration for the eventsc application:
app = 'eventsc'
primary_region = 'ord'
console_command = '/rails/bin/rails console'
swap_size_mb = 512

[build]

[env]
  DATABASE_URL = 'sqlite3:///data/production.sqlite3'
  PORT = '8080'
 
[processes]
  app = './bin/rails server'

[[mounts]]
  source = 'data'
  destination = '/data'
  auto_extend_size_threshold = 80
  auto_extend_size_increment = '1GB'
  auto_extend_size_limit = '10GB'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    interval = '10s'
    timeout = '2s'
    grace_period = '5s'
    method = 'GET'
    path = '/up'
    protocol = 'http'
    tls_skip_verify = false

    [http_service.checks.headers]
      X-Forwarded-Proto = 'https'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
